name: Cradle
options:
  bundleIdPrefix: com.cradleterm
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    PRODUCT_NAME: Cradle
    MARKETING_VERSION: "1.1.1"
    CURRENT_PROJECT_VERSION: "3"
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    CODE_SIGN_IDENTITY: "Developer ID Application"
    CODE_SIGN_STYLE: Manual
    DEVELOPMENT_TEAM: H5A65VHQU7
    PRODUCT_BUNDLE_IDENTIFIER: com.cradleterm.app
    ENABLE_HARDENED_RUNTIME: YES

packages:
  SwiftTerm:
    url: https://github.com/migueldeicaza/SwiftTerm.git
    from: "1.0.0"

targets:
  Cradle:
    type: application
    platform: macOS
    sources:
      - path: Cradle
        excludes:
          - "Resources/shell-integration/**"
      - path: Cradle/Resources/shell-integration
        type: folder
        buildPhase: resources
    settings:
      base:
        INFOPLIST_FILE: Cradle/Info.plist
        CODE_SIGN_ENTITLEMENTS: Cradle/Cradle.entitlements
        ENABLE_HARDENED_RUNTIME: true
    dependencies:
      - package: SwiftTerm
    entitlements:
      path: Cradle/Cradle.entitlements
      properties:
        com.apple.security.app-sandbox: false
        com.apple.security.cs.allow-unsigned-executable-memory: true
        com.apple.security.cs.disable-library-validation: true
        com.apple.security.cs.allow-jit: true
